// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnew0PUvcXtK-fl5ocTkfzc3-ouEVG66E',
    appId: '1:662723388518:web:4ec50350c641cd866079a7',
    messagingSenderId: '662723388518',
    projectId: 'fish-counter-55a99',
    authDomain: 'fish-counter-55a99.firebaseapp.com',
    storageBucket: 'fish-counter-55a99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAMzK_M7p1JmKj3fi-xhmlT0uRq1bziQ',
    appId: '1:662723388518:android:3a9c01d8a06d5cc66079a7',
    messagingSenderId: '662723388518',
    projectId: 'fish-counter-55a99',
    storageBucket: 'fish-counter-55a99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAqGDL1FjackYmJArDgC6EArI2zkOsnw',
    appId: '1:662723388518:ios:4ffaa185456264796079a7',
    messagingSenderId: '662723388518',
    projectId: 'fish-counter-55a99',
    storageBucket: 'fish-counter-55a99.firebasestorage.app',
    iosBundleId: 'com.yukon.fishcounter',
  );
}
